<a href="https://colab.research.google.com/github/Bonkus5/MachineLearning/blob/master/Steady_State_probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#HW3_Q1_steady state porbabilty
import numpy as np 
print('HW3_Q1')
l0=3
l1=2
l2=1

mu1=1
mu2=2
mu3=2

Pm=np.array([[-l0,l0,0,0],
             [mu1,-(l1+mu1),l1,0],
             [0,mu2,-(l2+mu2), l2],
             [0,0,mu3,-mu3]])
print(Pm)
Pm[0:,3]=1
print()
print(Pm)
Pmi = np.linalg.inv(Pm)
print(Pmi)
b = np.zeros(4)
b[4-1]=1
print(b)
sspi=b@Pmi
print('Steady State Probability = ', sspi)
print(sspi.sum())

#L
z = [0,1,2,3]
Lm=np.reshape(z,(4,1))
print(Lm)
L = sspi@Lm
print("L = ", L.sum())

#Lambda_eff
a = [3,2,1]
lbd012=np.reshape(a,(3,1))
#print(lbd012)
lbde = sspi[0:3]@lbd012
print("lambda_eff =", lbde.sum())
W = L/lbde.sum()
print("W = ", W)
print()

#HW3_Q2
import numpy as np 
print('HW3_Q2')
l0=4
l1=3
l2=2
l3=2
l4=3
l5=1
l6=2
l7=1
l8=2
l9=1

mu1=1
mu2=1
mu3=1
mu4=2
mu5=2
mu6=2
mu7=3
mu8=3
mu9=3
mu10=4

pm2=np.array([[-l0,l0,0,0,0,0,0,0,0,0,0],
              [mu1,-(l1+mu1),l1,0,0,0,0,0,0,0,0],
              [0,mu2,-(l2+mu2),l2,0,0,0,0,0,0,0],
              [0,0,mu3,-(l3+mu3),l3,0,0,0,0,0,0],
              [0,0,0,mu4,-(l4+mu4),l4,0,0,0,0,0],
              [0,0,0,0,mu5,-(l5+mu5),l5,0,0,0,0],
              [0,0,0,0,0,mu6,-(l6+mu6),l6,0,0,0],
              [0,0,0,0,0,0,mu7,-(l7+mu7),l7,0,0],
              [0,0,0,0,0,0,0,mu8,-(l8+mu8),l8,0],
              [0,0,0,0,0,0,0,0,mu9,-(l9+mu9),l9],
              [0,0,0,0,0,0,0,0,0,mu10,-mu10]])
print(pm2)
pm2[0:,10]=1
print()
print(pm2)
pm2i = np.linalg.inv(pm2)
print(pm2i)
b2 = np.zeros(11)
b2[11-1]=1
print(b2)
sspi2=b2@pm2i
print('Steady State Probability = ', sspi2)
print(sspi2.sum())

#L
z = [0,1,2,3,4,5,6,7,8,9,10]
Lm2=np.reshape(z,(11,1))
print(Lm2)
L2 = sspi2@Lm2
print("L = ", L2.sum())

#Lambda_eff
a = [4, 3, 2, 2, 3, 1, 2, 1, 2, 1]
lbd012_2=np.reshape(a,(10,1))
#print(lbd012)
lbde_2 = sspi2[0:10]@lbd012_2
print("lambda_eff =", lbde_2.sum())
W2 = L2/lbde_2.sum()
print("W_Q2 = ", W2)
print()

HW3_Q1
[[-3  3  0  0]
 [ 1 -3  2  0]
 [ 0  2 -3  1]
 [ 0  0  2 -2]]

[[-3  3  0  1]
 [ 1 -3  2  1]
 [ 0  2 -3  1]
 [ 0  0  2  1]]
[[-0.44117647 -0.32352941  0.17647059  0.58823529]
 [-0.14705882 -0.44117647  0.05882353  0.52941176]
 [-0.05882353 -0.17647059 -0.17647059  0.41176471]
 [ 0.11764706  0.35294118  0.35294118  0.17647059]]
[0. 0. 0. 1.]
Steady State Probability =  [0.11764706 0.35294118 0.35294118 0.17647059]
1.0
[[0]
 [1]
 [2]
 [3]]
L =  1.5882352941176472
lambda_eff = 1.411764705882353
W =  [1.125]

HW3_Q2
[[-4  4  0  0  0  0  0  0  0  0  0]
 [ 1 -4  3  0  0  0  0  0  0  0  0]
 [ 0  1 -3  2  0  0  0  0  0  0  0]
 [ 0  0  1 -3  2  0  0  0  0  0  0]
 [ 0  0  0  2 -5  3  0  0  0  0  0]
 [ 0  0  0  0  2 -3  1  0  0  0  0]
 [ 0  0  0  0  0  2 -4  2  0  0  0]
 [ 0  0  0  0  0  0  3 -4  1  0  0]
 [ 0  0  0  0  0  0  0  3 -5  2  0]
 [ 0  0  0  0  0  0  0  0  3 -4  1]
 [ 0  0  0  0  0  0  0  0  0  4 -4]]

[[-4  4  0  0  0  0  0  0  0  0  1]
 [ 1 -4  3  0  0  0  0  0  0  0  1]
 [ 0  